#!/bin/bash

set -e

# Get rid of old install maybe
if [ -d venv ]; then
    rm -r venv
fi

# Reset / grab a new one
virtualenv venv
source venv/bin/activate
pip install jupyter notebook
jupyter nbextension enable --py --sys-prefix widgetsnbextension

# Install local files
pip install -e .
jupyter nbextension install --py --symlink --sys-prefix ipyleaflet
jupyter nbextension enable --py --sys-prefix ipyleaflet
